name: Upload schema to wiki

on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Copy .env.example
              run: |
                  cp .env.example .env

            - name: Start postgres
              run: |
                  echo $TMPDIR
                  TMPDIR=/private$TMPDIR docker-compose up -d

            - name: Wait for docker for 20 secs
              run: sleep 20

            - name: Install Go
              uses: actions/setup-go/@v2
              with:
                  go-version: 1.16

            - name: Install planter
              run: |
                  go get -u github.com/achiku/planter

            - name: Run planter
              run: |
                  planter postgres://postgres:password@localhost/postgres?sslmode=disable --schema=public --output schema.uml

            - name: Generate PNG Diagram from uml
              uses: cloudbees/plantuml-github-action@master
              with:
                  args: -v -tpng schema.uml

            - name: Upload Schema to the Wiki
              uses: kai-tub/external-repo-sync-action@v1
              with:
                  source-directory: '.'
                  include-patterns: 'schema.png schema.uml'
              env:
                  GH_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
